name: CI
on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

defaults:
  run:
    working-directory: 'stonesoupkitchen.linuxgsm'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: 'stonesoupkitchen.linuxgsm'

      - name: Yamllint
        run: |
          docker run --rm -i -v $(pwd):/ws -w /ws docker.io/stonesoupkitchen/yamllint:latest .

      - name: Ansible Lint
        run: |
          mkdir -p .cache/roles
          ln -s ../.. .cache/roles/stonesoupkitchen.linuxgsm
          docker run --rm -i -v $(pwd):/ws -w /ws docker.io/stonesoupkitchen/ansible-lint:latest
